languageCode = "de"
languageName = "Deutsch"
languageDirection = "ltr"
weight = 2

title = "Felix Thiele"

[params]
  dateFormat = "02.01.2006"
  description = "Persöniche Website von Felix Thiele - IT & Organisationsarchitektur, Plattform-Engineering und Technologiestrategie"

[params.author]
  name = "Felix Thiele"
  image = "img/author.jpg"
  headline = "IT Consultant, Software Architekt und Team Lead"
  bio = "Felix ist Senior Consultant bei [INNOQ](https://www.innoq.com) und hat über 10 Jahren Erfahrung in diversen Rollen in IT-Consulting-Projekten gesammelt. Heute unterstützt er Kunden im Bereich IT- und Organisationsarchitektur, Plattformen und Technologiestrategie."
  links = [
    { bluesky = "https://bsky.app/profile/felixthiele.bsky.social"},
    { linkedin = "https://linkedin.com/in/felixthiele" },
    { github = "https://github.com/felixthiele" }
  ]
