languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Felix Thiele"

[params]
  dateFormat = "Jan 2, 2006"
  description = "Personal Website of Felix Thiele - IT & Organizational Architecture, Platform-Engineering and Technology Strategy"

[params.author]
  name = "Felix Thiele"
  image = "img/author.jpg"
  headline = "IT Consultant, Software Architect and Team Lead"
  bio = "Felix is a Senior Consultant at [INNOQ](https://www.innoq.com/en/) and accumulated 10 years of experience in various roles within IT-consulting projects. Currently, he helps clients with their IT architecture, organizational structure, platforms, and technology strategy."
  links = [
    { bluesky = "https://bsky.app/profile/felixthiele.bsky.social"},
    { linkedin = "https://linkedin.com/in/felixthiele" },
    { github = "https://github.com/felixthiele" }
  ]
